---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: gannett/gci-centos7

suites:
  - name: default
    run_list:
      - recipe[gd-test-helper::default]
      - recipe[base-centos]
      - recipe[tyk::default]
    attributes:
    chef_client:
      config:
        log_level: ":debug"

  - name: gateway
    run_list:
      - recipe[gd-test-helper::default]
      - recipe[base-centos]
      - recipe[tyk::install_redis]
      - recipe[tyk::install_mongo]
      - recipe[tyk::install_gateway]
    attributes:
    chef_client:
      config:
        log_level: ":debug"

  - name: dashboard
    run_list:
      - recipe[gd-test-helper::default]
      - recipe[base-centos]
      - recipe[tyk::install_redis]
      - recipe[tyk::install_mongo]
      - recipe[tyk::install_dashboard]
    attributes:
    chef_client:
      config:
        log_level: ":debug"

  - name: pump
    run_list:
      - recipe[gd-test-helper::default]
      - recipe[base-centos]
      - recipe[tyk::install_redis]
      - recipe[tyk::install_mongo]
      - recipe[tyk::install_pump]
    attributes:
    chef_client:
      config:
        log_level: ":debug"

  - name: sink
    run_list:
      - recipe[gd-test-helper::default]
      - recipe[base-centos]
      - recipe[tyk::install_redis]
      - recipe[tyk::install_mongo]
      - recipe[tyk::install_sink]
    attributes:
    chef_client:
      config:
        log_level: ":debug"
